### PR TITLE
Add `tokenizeLetDeclaration` option

### PR DESCRIPTION
**Pull request by sosukesuzuki**

### CODE REVIEW

**Comment by sosukesuzuki** [comment]
I merge this and will release new minor

**Comment by fisker** [comment]
I was going to ask for tests. 😄

**Comment by sosukesuzuki** [comment]
@fisker How did you release this package..? I run `yarn release` on `./packages/angular-html-parser`, then an error has occurred...

```
yarn release --release-as minor
yarn run v1.22.19
$ standard-version --release-as minor
/home/sosukesuzuki/ghq/github.com/prettier/angular-html-parser/packages/angular-html-parser/node_modules/cliui/build/index.cjs:291
const stringWidth = require('string-width');
                    ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/sosukesuzuki/ghq/github.com/prettier/angular-html-parser/packages/angular-html-parser/node_modules/string-width/index.js from /home/sosukesuzuki/ghq/github.com/prettier/angular-html-parser/packages/angular-html-parser/node_modules/cliui/build/index.cjs not supported.
Instead change the require of index.js in /home/sosukesuzuki/ghq/github.com/prettier/angular-html-parser/packages/angular-html-parser/node_modules/cliui/build/index.cjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/sosukesuzuki/ghq/github.com/prettier/angular-html-parser/packages/angular-html-parser/node_modules/cliui/build/index.cjs:291:21)
    at Object.<anonymous> (/home/sosukesuzuki/ghq/github.com/prettier/angular-html-parser/packages/angular-html-parser/node_modules/yargs/build/index.cjs:2861:12)
    at Object.<anonymous> (/home/sosukesuzuki/ghq/github.com/prettier/angular-html-parser/packages/angular-html-parser/node_modules/yargs/index.cjs:5:30)
    at Object.<anonymous> (/home/sosukesuzuki/ghq/github.com/prettier/angular-html-parser/packages/angular-html-parser/node_modules/standard-version/command.js:5:15)
    at Object.<anonymous> (/home/sosukesuzuki/ghq/github.com/prettier/angular-html-parser/packages/angular-html-parser/node_modules/standard-version/bin/cli.js:8:21) {
  code: 'ERR_REQUIRE_ESM'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by fisker** [comment]
I saw this error too, but after I reinstall the deps, the error was gone...

**Comment by fisker** [comment]
Released.

**Comment by sosukesuzuki** [comment]
@fisker Thank you. Are you going to implement the Prettier side? If not, I can work on it this weekend.

**Pull request merged**
